version: "3.5"

services:
  angular:
    build: ./web
    volumes:
      - "./web:/usr/src/app"
    ports:
      - "4200:4200"
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
  nest:
    build: ./server
    volumes:
      - "./server:/usr/src/server"
    ports:
      - "3000:3000"
    command: >
      bash -c "npm install && npm run start:dev"
  database:
    image: postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: borker
      POSTGRES_PASSWORD: borker123
